name: Pipeline Tools CLI
on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]

jobs:
  build:
    if: github.ref_type == 'tag' && contains(github.event.base_ref, 'master')
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o Código
        uses: actions/checkout@v6

      - name: Scan Dockerfile
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: Dockerfile
          failure-threshold: "warning"
      - name: Efetuando Login no Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }} 

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v4    

 
      - name: Building and Push Image to Hub Docker
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cloud-tools:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/cloud-tools:${{ github.ref_name }}


  scan:
    if: github.ref_type == 'tag' && contains(github.event.base_ref, 'master')
    needs: build
    runs-on: ubuntu-latest
    steps:          
      - name: Executar o Trivy
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          scan-type: "image"
          image-ref: "afmaia/cloud-tools:${{ github.ref_name }}"
          format: "sarif"
          output: "trivy-docker-result.sarif"
          severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"

      - name: Upload do resultado do Trivy
        uses: github/codeql-action/upload-sarif@v3
        with:
          category: docker-result
          sarif_file: trivy-docker-result.sarif

      